---
title: "Gov 50 Final Project"
author: "Joshua Parker"
description: "Analyzing the Impact of Base MSRP and Driving Range on Electric Vehicle Adoption"
output:
  distill::distill_article:
    self_contained: false
---



## Project thoughts

I am interested in exploring data related to the impact of the base Manufacturer's Suggested Retail Price (MSRP) and driving range of electric vehicles (EVs) on the adoption of EVs in legislative districts. As a passionate advocate for forging environmental progress, I want to better understand the relationships between the MSRP of EVs and consumer behavior to inform future decisions of manufacturers and government officials to catalyze the transition to renewable energy.

## Research proposal

Does the base MSRP and driving range of EVs have a causal effect on the adoption of EVs in legislative districts?

I hypothesize that legislative districts with lower base MSRP and higher driving range EVs are more likely to experience increased adoption of EVs. This is rooted in the belief that affordability and a strong battery range are attractive to the common customer. In contrast, legislative districts with higher base MSRP and lower driving range EVs may lack the economic accessibility to practical EVs, and thus, witness lower rates of EV adoption.

All research will be conducted using the publicly available Electric Vehicle Population data set from the Washington State Department of Licensing (DOL).

The explanatory variables of interest are base MSRP (base_msrp) and driving range (electric_range). Base MSRP is measured as the lowest MSRP for any trim level of the model in question. Driving range is measured as the distance the vehicle can travel purely on its electric charge.

The outcome variable of interest is EV adoption in legislative districts. This variable is not present in the raw data set, but will be measured as the count of registered EVs in a given legislative district.

If the analysis yields a negative and statistically significant coefficient for the base MSRP variable and a positive and statistically significant coefficient for the driving range variable, it would provide support for the hypothesis. This would suggest that, on average, EVs with lower base MSRPs and longer electric ranges are associated with a higher count of EVs in legislative districts. Such a pattern would align with the idea that addressing high costs and range anxiety through longer electric ranges positively influences consumer adoption decisions.

Conversely, if the coefficient for base MSRP is not statistically significant or positive, or the coefficient for driving range is not statistically significant or negative, it would suggest that there is no clear association between base MSRP, electric range and electric vehicle adoption. This could imply that other factors, such as vehicle design and charging infrastructure, may play a more prominent role in consumer adoption trends.

